services:
  server:
    image: simple_rest
    restart: always
    ports:
      - 8080:8080
  postgres:
    image: postgres:14.5
    restart: always
    ports:
      - "35432:5432"
    volumes:
      - ./data:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: ${SECURE_PASSWORD}
      POSTGRES_USER: user
      POSTGRES_DB: user
